name: tocenbough
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: fumieval/tocenbough@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 10
